# <span style="color:#c89911">Projeto:</span>  <span style="color:#5a7ab1">*Jobs and Salaries in Data Science*</span>

---

Banco usado (adiquirido pelo [kaggle](https://www.kaggle.com/)): [*jobs_in_data*](https://www.kaggle.com/datasets/hummaamqaasim/jobs-in-data)

---
## Colunas:

- <span style="color:#11c83f">work_year:</span>  O ano em que os dados foram registrados. Este campo indica o contexto temporal dos dados, importante para a compreensão das tendências salariais ao longo do tempo.

- <span style="color:#11c4c8">job_title:</span>  O título específico da função, como 'Cientista de Dados', 'Engenheiro de Dados' ou 'Analista de Dados'. Esta coluna é crucial para entender a distribuição salarial entre as diversas funções especializadas na área de dados.

- <span style="color:#11c83f">job_category:</span>  Uma classificação da função em categorias mais amplas para facilitar a análise. Isso pode incluir áreas como 'Análise de Dados', 'Aprendizado de Máquina', 'Engenharia de Dados', etc.

- <span style="color:#11c4c8">salary_currency:</span>  A moeda em que o salário é pago, como USD, EUR, etc. Isso é importante para a conversão de moeda e para entender o valor real do salário em um contexto global.

- <span style="color:#11c83f">salary:</span>  O salário bruto anual do cargo na moeda local. Este valor bruto do salário é fundamental para comparações salariais regionais diretas.

- <span style="color:#11c4c8">salary_in_usd:</span>  O salário bruto anual convertido para dólares americanos (USD). Essa conversão de moeda uniforme facilita comparações e análises salariais globais.

- <span style="color:#11c83f">employee_residence:</span>  O país de residência do funcionário. Este dado pode ser usado para explorar diferenças salariais geográficas e variações no custo de vida.

- <span style="color:#11c4c8">experience_level:</span>  Classifica o nível de experiência profissional do funcionário. As categorias comuns podem incluir "Iniciante", "Pleno", "Sênior" e "Executivo", fornecendo informações sobre como a experiência influencia o salário em funções relacionadas a dados.

- <span style="color:#11c83f">employment_type:</span>  Especifica o tipo de vínculo empregatício, como 'Tempo integral', 'Tempo parcial', 'Contrato', etc. Isso auxilia na análise de como diferentes modalidades de emprego afetam as estruturas salariais.

- <span style="color:#11c4c8">work_setting:</span>  O ambiente ou modalidade de trabalho, como 'Remoto', 'Presencial' ou 'Híbrido'. Esta coluna reflete o impacto dos ambientes de trabalho nos níveis salariais no setor de dados.

- <span style="color:#11c83f">company_location:</span>  O país onde a empresa está localizada. Isso ajuda a analisar como a localização da empresa afeta as estruturas salariais.

- <span style="color:#11c4c8">company_size:</span>  O tamanho da empresa empregadora, geralmente categorizado em pequeno (P), médio (M) e grande (G). Isso permite analisar como o tamanho da empresa influencia o salário.

## DataFrame em Python

Uma **estrutura de dados tabular** é uma forma de organizar informações em formato de **tabela**, composta por:

- **Linhas** (registros)
- **Colunas** (atributos ou variáveis)

Esse formato é semelhante a uma planilha do Excel ou a uma tabela de banco de dados.

Exemplo:

| Nome     | Idade | Profissão        |
|----------|--------|-----------------|
| Ana      | 25     | Cientista de Dados |
| Carlos   | 30     | Engenheiro      |

Cada linha representa um registro, e cada coluna representa uma característica desse registro.

---

Um **DataFrame** é uma estrutura de dados **bidimensional e tabular** fornecida pela biblioteca **Pandas** no Python.

Ele permite:

- Armazenar dados em formato de tabela
- Manipular dados (filtrar, ordenar, agrupar)
- Realizar análises estatísticas
- Limpar e transformar dados

O DataFrame é uma das estruturas mais importantes para análise de dados em Python.

---

## O DataFrame é amplamente utilizado em Ciência de Dados

O DataFrame é muito utilizado porque:

✔ Permite trabalhar facilmente com grandes volumes de dados  
✔ Possui funções para limpeza e tratamento de dados  
✔ Facilita a análise estatística  
✔ Integra-se com bibliotecas como:
- NumPy
- Matplotlib
- Seaborn
- Scikit-learn

Além disso, ele permite importar dados de diversos formatos:

- CSV
- Excel
- JSON
- Banco de dados SQL

Por isso, é uma ferramenta essencial para **Ciência de Dados e Análise de Dados**.

---

## Biblioteca necessária

Para trabalhar com DataFrames em Python, nesse projeto necessário instalar e importar a biblioteca:

```python
# Seu código aqui
    pip install pandas
```

In [9]:
import pandas as pd
df = pd.read_csv("jobs_in_data.csv")
df.head()
df.tail()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
9350,2021,Data Specialist,Data Management and Strategy,USD,165000,165000,United States,Senior,Full-time,Remote,United States,L
9351,2020,Data Scientist,Data Science and Research,USD,412000,412000,United States,Senior,Full-time,Remote,United States,L
9352,2021,Principal Data Scientist,Data Science and Research,USD,151000,151000,United States,Mid-level,Full-time,Remote,United States,L
9353,2020,Data Scientist,Data Science and Research,USD,105000,105000,United States,Entry-level,Full-time,Remote,United States,S
9354,2020,Business Data Analyst,Data Analysis,USD,100000,100000,United States,Entry-level,Contract,Remote,United States,L

# Tipos de Variáveis em Ciência de Dados

Em análise de dados, as variáveis são classificadas de acordo com o tipo de informação que representam. Elas podem ser **Qualitativas (Categóricas)** ou **Quantitativas (Numéricas)**.

---

### 1. Variáveis Qualitativas (Categóricas)

São variáveis que representam **características ou categorias**, e não números com significado matemático.

Elas se dividem em:

### Nominais

- Não possuem ordem natural.
- Servem apenas para classificação.
Mesmo que sejam representadas por números, esses números não indicam quantidade.

---

## Ordinais

- Possuem uma **ordem natural**.
- Indicam hierarquia ou nível.

---

# 2. Variáveis Quantitativas (Numéricas)

São variáveis que representam **valores numéricos** e permitem cálculos matemáticos.

Elas se dividem em:

## Discretas

- Assumem valores inteiros.
- Geralmente representam contagens.

## Contínuas

- Podem assumir qualquer valor dentro de um intervalo.
- Podem conter casas decimais.


| Tipo | Subtipo | Característica |
|------|---------|---------------|
| Qualitativa | Nominal | Sem ordem |
| Qualitativa | Ordinal | Com ordem |
| Quantitativa | Discreta | Valores inteiros |
| Quantitativa | Contínua | Valores decimais |

---

#### Executando o Código

In [10]:
df.info()
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 9355 entries, 0 to 9354
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           9355 non-null   int64
 1   job_title           9355 non-null   str
 2   job_category        9355 non-null   str
 3   salary_currency     9355 non-null   str
 4   salary              9355 non-null   int64
 5   salary_in_usd       9355 non-null   int64
 6   employee_residence  9355 non-null   str
 7   experience_level    9355 non-null   str
 8   employment_type     9355 non-null   str
 9   work_setting        9355 non-null   str
 10  company_location    9355 non-null   str
 11  company_size        9355 non-null   str
dtypes: int64(3), str(9)
memory usage: 877.2 KB

work_year             int64
job_title               str
job_category            str
salary_currency         str
salary                int64
salary_in_usd         int64
employee_residence      str
experience_level        str
employment_type         str
work_setting            str
company_location        str
company_size            str
dtype: object

# Informações Faltantes e Duplicadas em um Banco de Dados

Em Ciência de Dados, antes de realizar qualquer análise, é fundamental verificar a **qualidade dos dados**. Dois problemas muito comuns são:

- Valores nulos (informações faltantes)
- Dados duplicados

Esses fatores podem comprometer análises, gerar resultados incorretos e prejudicar modelos de Machine Learning.

---

# 1. Valores Nulos (Informações Faltantes)

## O que são valores nulos?

Valores nulos representam **dados ausentes ou não informados** em uma base de dados.

No Pandas, eles geralmente aparecem como:

- `NaN` (Not a Number)
- `None`

### Exemplo:

| Nome   | Idade | Salário |
|--------|--------|---------|
| Ana    | 25     | 3000    |
| Carlos | NaN    | 4000    |
| Maria  | 28     | NaN     |

---

## Por que analisar valores nulos?

Porque eles podem:

- Distorcer médias e estatísticas
- Causar erros em cálculos
- Prejudicar modelos de Machine Learning
- Indicar falhas na coleta de dados

Antes da análise, é necessário decidir se os valores nulos serão:

- Removidos
- Substituídos (por média, mediana, moda, etc.)
- Mantidos (dependendo do caso)

---

# 2. Dados Duplicados

## O que são dados duplicados?

São registros ou informações repetidas dentro do banco de dados.

### Exemplo:

| Nome | Idade | Cargo |
|------|--------|--------|
| João | 30     | Analista |
| João | 30     | Analista |

---

## Por que analisar duplicatas?

Dados duplicados podem:

- Inflar resultados estatísticos
- Gerar contagens incorretas
- Comprometer análises de frequência
- Prejudicar modelos preditivos

Por isso, é essencial verificar e tratar duplicações antes de qualquer análise.

---

##### Executando o Código

In [11]:
df.isnull().sum()
df.T.duplicated()

work_year             False
job_title             False
job_category          False
salary_currency       False
salary                False
salary_in_usd         False
employee_residence    False
experience_level      False
employment_type       False
work_setting          False
company_location      False
company_size          False
dtype: bool

## Método `describe()` no Pandas

O método `describe()` é utilizado para gerar um **resumo estatístico** das colunas de um DataFrame.  
Ele é muito importante na etapa de **Análise Exploratória de Dados (EDA)**, pois fornece uma visão geral rápida dos dados numéricos.

---

### Quais estatísticas são calculadas?

Ao executar:

In [12]:
df.describe()

         work_year         salary  salary_in_usd
count  9355.000000    9355.000000    9355.000000
mean   2022.760449  149927.981293  150299.495564
std       0.519470   63608.835387   63177.372024
min    2020.000000   14000.000000   15000.000000
25%    2023.000000  105200.000000  105700.000000
50%    2023.000000  143860.000000  143000.000000
75%    2023.000000  187000.000000  186723.000000
max    2023.000000  450000.000000  450000.000000

# Tradução das Colunas para Português (Apresentação ao Público)

##  Contexto

Como os resultados da análise serão apresentados em uma **feira aberta à comunidade**, é importante garantir que as informações estejam claras e acessíveis para pessoas que **não possuem familiaridade com termos técnicos em inglês**.

Traduzir os nomes das colunas:

- ✔ Facilita a compreensão
- ✔ Torna a apresentação mais inclusiva
- ✔ Mantém clareza e coerência
- ✔ Preserva o significado técnico dentro da Ciência de Dados

---

## Dicionário de Tradução das Colunas

A estratégia utilizada foi criar um **dicionário em Python**, onde:

- A chave → é o nome original da coluna (em inglês)
- O valor → é o novo nome traduzido (em português)

---

##### Código Executado:

In [ ]:
# Dicionario de traducao dos nomes das colunas
novos_nomes = {
    "work_year": "ano_trabalho",
    "job_title": "cargo",
    "job_category": "categoria_cargo",
    "salary_currency": "moeda_salario",
    "salary": "salario",
    "salary_in_usd": "salario_dolar",
    "employee_residence": "residencia_funcionario",
    "experience_level": "nivel_experiencia",
    "employment_type": "tipo_contrato",
    "work_setting": "modelo_trabalho",
    "company_location": "localizacao_empresa",
    "company_size": "porte_empresa"
}

# Aplicando a traducao das colunas
df_pt_br = df.rename(columns=novos_nomes)

# Exibindo os novos nomes das colunas
print(df_pt_br.columns)

Index(['ano_trabalho', 'cargo', 'categoria_cargo', 'moeda_salario', 'salario',
       'salario_dolar', 'residencia_funcionario', 'nivel_experiencia',
       'tipo_contrato', 'modelo_trabalho', 'localizacao_empresa',
       'porte_empresa'],
      dtype='str')

## Uso do módulo `datetime` e análise temporal

### O que é o módulo `datetime`?
O módulo `datetime` do Python permite trabalhar com datas e horários de forma estruturada,
possibilitando conversões, comparações e cálculos temporais.

Na Ciência de Dados, ele é fundamental para:
- Analisar séries temporais
- Identificar tendências ao longo do tempo
- Comparar períodos distintos
- Entender o contexto histórico dos dados

No pandas, o `datetime` é amplamente utilizado por meio da função `pd.to_datetime()`,
que converte dados textuais em objetos de data reconhecidos pelo Python.

In [17]:
# Convertendo a coluna de ano para o tipo datetime
df_pt_br['ano_trabalho'] = pd.to_datetime(
    df_pt_br['ano_trabalho'],
    format='%Y'
)
# Exibindo o intervalo temporal do banco de dados
print("Início:", df_pt_br['ano_trabalho'].min())
print("Fim:", df_pt_br['ano_trabalho'].max())

Início: 2020-01-01 00:00:00
Fim: 2023-01-01 00:00:00

### Conclusão

A utilização do módulo `datetime` é essencial para garantir análises temporais corretas,
permitindo interpretar os dados dentro de um contexto histórico e facilitar comparações
significativas ao longo do tempo.

## Comparação de colunas de salário

### Contexto
Em bases de dados internacionais, os salários podem estar registrados em diferentes moedas,
de acordo com o país de residência do funcionário ou localização da empresa.

Para possibilitar análises comparativas entre países e regiões, é comum manter:
- Um valor de salário na moeda original (`salary`)
- Um valor convertido para uma moeda padrão, geralmente o dólar americano (`salary_in_usd`)

Essa padronização monetária é essencial para análises estatísticas globais e tomada de decisão.

In [18]:
# Visualizando as colunas relacionadas a salário
df[['salary', 'salary_in_usd', 'salary_currency']].head(10)

   salary  salary_in_usd salary_currency
0   88000          95012             EUR
1  186000         186000             USD
2   81800          81800             USD
3  212000         212000             USD
4   93300          93300             USD
5  130000         130000             USD
6  100000         100000             USD
7  224400         224400             USD
8  138700         138700             USD
9  210000         210000             USD

### Conclusão

A padronização monetária em USD é uma prática fundamental em bases de dados internacionais,
pois garante consistência, comparabilidade e confiabilidade nas análises estatísticas e
no suporte à tomada de decisão em contextos globais.

# **Análise das categorias profissionais**

Analise as categorias profissionais presentes na coluna `job_category`. O objetivo é identificar quais áreas da Ciência de Dados possuem maior número de registros no banco de dados e discutir a relevância dessas categorias no contexto do mercado brasileiro.

Execute o código na célula seguinte para gerar a tabela de contagens por categoria e ordená‑la do maior para o menor.

In [19]:
# Agrupar por categoria e contar
df_categoria = (
    df_pt_br.groupby('categoria_cargo')
      .size()
      .reset_index(name='quantidade')
      .sort_values(by='quantidade', ascending=False)
)

# Exibir o resultado
df_categoria

                  categoria_cargo  quantidade
7       Data Science and Research        3014
4                Data Engineering        2260
2                   Data Analysis        1457
9         Machine Learning and AI        1428
8       Leadership and Management         503
0            BI and Visualization         313
3  Data Architecture and Modeling         259
5    Data Management and Strategy          61
6     Data Quality and Operations          55
1              Cloud and Database           5